$(function(){$(".accordion").accordion({collapsible:!0,heightStyle:"content"})});$(".c-services-2 .accordion > h3").prepend('<span class="accord-icon"></span>');$(window).scroll(startCounter);
function startCounter(){var a=$(window).scrollTop(),b=$(".c-countup .c-countup__item").offset().top-1E3,c=$(".c-services").offset().top;a>=b&&a<c&&($(window).off("scroll",startCounter),$(".c-countup .c-countup__item").each(function(){var a=$(this),b=a.attr("data-count");$({countNum:a.children("div").text()}).one().animate({countNum:b},{duration:2E3,easing:"linear",step:function(){a.children("div").text(Math.floor(this.countNum))},complete:function(){a.children("div").text(this.countNum)}})}))}
jQuery(function(a){var b=!0,c=!0;hidden=!0;if(1199>=a(window).width()||1==b)a(".menu-trigger").click(function(b){b.preventDefault();a(".c-main-menu").offset();a(".c-main-menu").width();a("body");a(".c-main-menu").animate({left:0},350);a("body").animate({left:200},350,function(){a("body").addClass("fade")})}),b=!1;else if(1199<a(window).width()||0==b)a(".menu-trigger").unbind("click"),b=!0;if(1199<a(window).width()||1==c)a(document).on("scroll",function(b){a("div.object1").remove();b.preventDefault();
var c=a(document).scrollTop();a(".c-nav .c-main-menu .c-main-menu__link").each(function(){var b=a(this),f=a(b.attr("href")),d=f.offset().top-80;d<=c&&d+220+f.height()>c?(a(".c-nav .c-main-menu  .c-main-menu__link").removeClass("trala"),b.one().addClass("trala"),b.prepend('<div class="object1"></div>'),f=b.parent().width(),a("div.object1").width(f),a("div.object1").show().stop().animate({opacity:1},700),b.show().stop().animate({opacity:1},1E3)):b.removeClass("trala")})}),c=!1;else if(1199>=a(window).width()||
0==c)a(document).off("scroll",onScroll),c=!0;a(".c-nav .c-main-menu .c-main-menu__link").on("click",function(b){a(this).hasClass("trala")||a("div.object1").remove();1199>=a(window).width()?(b.preventDefault(),a("html,body").animate({scrollTop:a(a.attr(this,"href")).offset().top-60},1E3,function(){a(".c-main-menu").animate({left:-200},{duration:200,queue:!1});a("html,body").animate({left:0},{duration:200,quee:!1})})):1199<a(window).width()&&a("html,body").unbind("animate");if(1199<a(window).width()){b.preventDefault();
a(document).off("scroll");a(".c-nav .c-main-menu  a").each(function(){a(this).removeClass("trala")});a(this).addClass("trala");a(this).prepend('<div class="object1"></div>');var c=this.hash;$target=a(c);a("html, body").stop().animate({scrollTop:$target.position().top-80},1200,"swing",function(){location.hash=c;a(document).on("scroll",onScroll)})}else if(1199>=a(window).width())a(document).on("scroll")});onResize=function(){1199>=a(window).width()?a(".c-nav .c-main-menu").css({left:-200}):1199<a(window).width()&&
(a(".c-nav .c-main-menu").css({left:0}),a("body").css({left:0}))};a(document).ready(onResize);a(window).on("resize",onResize)});
$(window).scroll(function(){280<$(window).scrollTop()?($(".c-nav").addClass("fixed"),$(".c-main-menu__link").addClass("c-main-menu__link--font"),$(".c-main-menu h1 a").css("color","#999999"),$(".o-card").css("filter","brightness(60%)"),$(".c-main-menu__search").css("filter","brightness(60%)")):($(".c-nav").removeClass("fixed"),$(".c-main-menu__link").removeClass("c-main-menu__link--font"),$(".c-main-menu h1 a").css("color","white"),$(".o-card").css("filter",""),$(".c-main-menu__search").css("filter",
""))});
$(document).ready(function(){function a(){return c.find("div.c-main-header__slide")}function b(b){b&&(g=b);$interval=setInterval(function(){var b=c.find("div.c-main-header__slide.active_one").index(),e=d.find("li.c-header-switch__item.active_two").index();a().eq(b).removeClass("active_one");a().eq(b).fadeOut(1E3);d.find("li.c-header-switch__item").eq(e).removeClass("active_two");a().length==b+1&&(b=-1);d.find("li.c-header-switch__item").length==e+1&&(e=-1,$(".c-header-switch__item").last().children("div:nth-child(1)").css("width","0"),
$(".c-header-switch__item").children("div:nth-child(1)").css("width","0"),$(".c-header-switch__item").children("div.c-header-switch__bar").hide(),$(".c-header-switch__item").children("div.c-header-switch__bar").show());a().eq(b+1).fadeIn(1E3);a().eq(b+1).addClass("active_one");d.find("li.c-header-switch__item").eq(e+1).addClass("active_two");a();$(".c-header-switch__item").eq(e+1).children("div:nth-child(1)").stop().css({width:"0%"}).animate({width:"100%"},g)},6E3)}var c=$(".c-main-header"),d=$(".c-main-header"),
g=5300;$(".c-header-switch__item").first().children("div:nth-child(1)").clearQueue().stop().css({width:"0%"}).animate({width:"100%"},g);a().fadeOut(0);a().first().addClass("active_one");a().first().fadeIn(1E3);d.find("li.c-header-switch__item").first().addClass("active_two");$(function(){b()})});function initMap(){var a={lat:-7.97366,lng:112.663896},b=new google.maps.Map(document.getElementById("map"),{zoom:16,center:a});new google.maps.Marker({position:a,map:b})}window.onload=initMap;
$(".open-map").on("click",function(){$(".map-icon").fadeOut("2000");$(".open-map").fadeOut("2000");$(".o-hr--map").fadeOut("2000");$(".map-section").animate({height:800},{duration:500,complete:function(){$(".map-section__mask").animate({opacity:"0"},{duration:500,complete:function(){$(".map-section__mask").hide();$(".map").animate({opacity:"1"},{duration:2E3,complete:function(){}})}})}})});$(".mobile-menu__item--search").click(function(a){a.preventDefault();$(".c-form__search").addClass("search_active").fadeIn(slow)});
$(".c-form__cancel").click(function(a){a.preventDefault();$(".c-form__search").removeClass("search_active")});$("html,body").niceScroll({cursorcolor:"#fff",cursorwidth:"8px",cursoropacitymax:.5,cursorborder:"1px solid darkgrey",background:"",horizrailenabled:!1});$(window).scroll($.debounce(250,!0,function(){$("#scrollMsg").html("SCROLLING!")}));
$(window).scroll($.debounce(250,function(){var a=$(document).scrollTop(),b=$("html, body");200<=a?$(".back-to-top").stop(b).animate({right:"10px"},500,function(){}):200>a&&$(".back-to-top").stop(b).animate({right:"-50px"},500,function(){})}));$("a[href='#top']").click(function(a){a.preventDefault();$("html, body").animate({scrollTop:0},"slow");return!1});